@startuml active

(*) -> "需求分析"

if "符合条件" then
    -> [true] "面向对象分析\n定制代码风格"
    -> "实际编码"
    --> "查找资料"
    --> "实际编码"
    --> "参考群样\n例内容"
    -> "调试"
    --> "实际编码"
    -> "代码分析"
    -> "博客总结"
    -> (*)
else
    --> [false] "与客户(助教)\n沟通"
    --> "需求分析"

@enduml